theme: jekyll-theme-minimal
title: "PostDoc Potential — From PhD to PostDoc in Earth Sciences"
# logo: /assets/kbush58-stick-people-2324013_1920.png
description: "Find postdoc opportunities, career guidance, and community support for early-career researchers in Earth, atmospheric, ocean and climate science"
avatar: true
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title-on-all-pages: true
image: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

exclude:
  - _archive/
  - docs/
  - scripts/