theme: jekyll-theme-minimal
title: Home
logo: /assets/kbush58-stick-people-2324013_1920.png
#description: A platform created for and by early-career researchers navigating postdoctoral research positions in Earth Science.
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - index.md
repo_info: false
nav: true
remote_theme: pages-themes/minimal@v0.2.0
title-on-all-pages: true
image: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one