theme: jekyll-theme-minimal
title: PostDoc Potential
# logo: /assets/kbush58-stick-people-2324013_1920.png
description: A platform created for and by early-career researchers navigating postdoctoral research positions in Earth Science.
av: true
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title-on-all-pages: true
image: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one